name: CI
on: [push]
jobs:
  CompilePDF:
    runs-on: ubuntu-latest
    name: Compile resume.pdf from resume.tex
    steps:
      - uses: actions/checkout@v2
      - name: Create .pdf compiler
        run: docker build --tag compiler .
      - name: Compile PDF
        run: docker run --mount type=bind,source=$(pwd)/cv,destination=/cv compiler
      - uses: actions/upload-artifact@v2
        with:
          name: Commit PDF
          path: cv/resume.pdf
  CommitPDF:
    runs-on: ubuntu-latest
    name: Commit resume.pdf to GitHub Pages
    steps:
      - uses: actions/checkout@v2
        with:
          ref: github_pages_branch
      - name: Download resume from builder
        uses: actions/download-artifact@v2
        with:
          name: resume.pdf
        #another compile-check
